// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type AnnotatedArticle struct {
	ArticleID  int32     `json:"article_id"`
	Annotation string    `json:"annotation"`
	CreatedAt  time.Time `json:"created_at"`
}

type Article struct {
	ID        int32          `json:"id"`
	SrcID     string         `json:"src_id"`
	Title     sql.NullString `json:"title"`
	Content   sql.NullString `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
}

type ArticleEntity struct {
	ID         sql.NullInt32  `json:"id"`
	ArticleID  int32          `json:"article_id"`
	Entity     sql.NullString `json:"entity"`
	EntityType sql.NullString `json:"entity_type"`
	Counts     int16          `json:"counts"`
	CreatedAt  time.Time      `json:"created_at"`
}

type EnewsRawArticle struct {
	AddedID      sql.NullString `json:"added_id"`
	SrcID        sql.NullString `json:"src_id"`
	ArticleType  sql.NullString `json:"article_type"`
	ImgUrl       sql.NullString `json:"img_url"`
	Title        sql.NullString `json:"title"`
	PublishTime  sql.NullTime   `json:"publish_time"`
	PublishDate  sql.NullTime   `json:"publish_date"`
	Category     sql.NullString `json:"category"`
	Author       sql.NullString `json:"author"`
	ContentRaw   sql.NullString `json:"content_raw"`
	ContentText  sql.NullString `json:"content_text"`
	TagsRaw      sql.NullString `json:"tags_raw"`
	TagsText     sql.NullString `json:"tags_text"`
	Summary      sql.NullString `json:"summary"`
	LikeCount    sql.NullString `json:"like_count"`
	DislikeCount sql.NullString `json:"dislike_count"`
	RatingCount  sql.NullString `json:"rating_count"`
	ViralCount   sql.NullString `json:"viral_count"`
	CommentCount sql.NullString `json:"comment_count"`
	TopicID      sql.NullInt32  `json:"topic_id"`
	PostedAt     sql.NullTime   `json:"posted_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type EntityType struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Language    string         `json:"language"`
	CreatedAt   time.Time      `json:"created_at"`
}

type StageExtractedEntity struct {
	ArticleID  int32          `json:"article_id"`
	Entity     sql.NullString `json:"entity"`
	EntityType sql.NullString `json:"entity_type"`
	Counts     int16          `json:"counts"`
	CreatedAt  time.Time      `json:"created_at"`
}

type UniqueEntity struct {
	ID         sql.NullInt32 `json:"id"`
	Name       string        `json:"name"`
	EntityType string        `json:"entity_type"`
	CreatedAt  time.Time     `json:"created_at"`
}
