// Code generated by sqlc. DO NOT EDIT.
// source: unique_entities.sql

package db

import (
	"context"
	"database/sql"
)

const createUniqueEntity = `-- name: CreateUniqueEntity :exec
INSERT INTO unique_entities (
    name
    , entity_type_id
) VALUES (
    $1, $2 
)
RETURNING id, name, entity_type_id, created_at
`

type CreateUniqueEntityParams struct {
	Name         sql.NullString `json:"name"`
	EntityTypeID sql.NullInt32  `json:"entity_type_id"`
}

func (q *Queries) CreateUniqueEntity(ctx context.Context, arg CreateUniqueEntityParams) error {
	_, err := q.exec(ctx, q.createUniqueEntityStmt, createUniqueEntity, arg.Name, arg.EntityTypeID)
	return err
}

const getUniqueEntities_ByEntityType = `-- name: GetUniqueEntities_ByEntityType :many
SELECT id, name, entity_type_id, created_at 
FROM unique_entities
WHERE entity_type_id = $1
`

func (q *Queries) GetUniqueEntities_ByEntityType(ctx context.Context, entityTypeID sql.NullInt32) ([]UniqueEntity, error) {
	rows, err := q.query(ctx, q.getUniqueEntities_ByEntityTypeStmt, getUniqueEntities_ByEntityType, entityTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UniqueEntity
	for rows.Next() {
		var i UniqueEntity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EntityTypeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniqueEntities_ByName = `-- name: GetUniqueEntities_ByName :many
SELECT id, name, entity_type_id, created_at 
FROM unique_entities 
WHERE name = $1
`

func (q *Queries) GetUniqueEntities_ByName(ctx context.Context, name sql.NullString) ([]UniqueEntity, error) {
	rows, err := q.query(ctx, q.getUniqueEntities_ByNameStmt, getUniqueEntities_ByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UniqueEntity
	for rows.Next() {
		var i UniqueEntity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EntityTypeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUniqueEntities_ByName_EntityType = `-- name: GetUniqueEntities_ByName_EntityType :one
SELECT id, name, entity_type_id, created_at
FROM unique_entities
WHERE 
    name = $1 
    AND entity_type_id = $2
`

type GetUniqueEntities_ByName_EntityTypeParams struct {
	Name         sql.NullString `json:"name"`
	EntityTypeID sql.NullInt32  `json:"entity_type_id"`
}

func (q *Queries) GetUniqueEntities_ByName_EntityType(ctx context.Context, arg GetUniqueEntities_ByName_EntityTypeParams) (UniqueEntity, error) {
	row := q.queryRow(ctx, q.getUniqueEntities_ByName_EntityTypeStmt, getUniqueEntities_ByName_EntityType, arg.Name, arg.EntityTypeID)
	var i UniqueEntity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EntityTypeID,
		&i.CreatedAt,
	)
	return i, err
}
