// @author: goodalg0s@gmail.com

package main

import (
	"database/sql"
	"time"
)

// The following structs are mapped with the built-in tables generated by the DDLs in `ddl.sql`.
// The structs are used to represent the rows of those tables within enews' GO application.

/*
	ARTICLE & ENTITY TABLES
*/

type Article struct {
	ID        int            `db:"id"`
	SrcID     int            `db:"src_id"`
	Title     sql.NullString `db:"title"`
	Content   sql.NullString `db:"content"`
	CreatedAt time.Time      `db:"created_at"`
}

type ExtractedArticle struct {
	ID        int            `db:"id"`
	ArticleID int            `db:"article_id"`
	Entities  sql.NullString `db:"entities"`
	CreatedAt time.Time      `db:"created_at"`
}

type TempExtractedArticle struct {
	ArticleID int            `db:"article_id"`
	Entities  sql.NullString `db:"entities"`
	CreatedAt time.Time      `db:"created_at"`
}

type ArticleEntity struct {
	ID         int       `db:"id"`
	ArticleID  int       `db:"article_id"`
	Entity     string    `db:"entity"`
	EntityType string    `db:"entity_type"`
	Counts     int       `db:"counts"`
	CreatedAt  time.Time `db:"created_at"`
}

type UniqueEntity struct {
	ID           int       `db:"id"`
	Name         string    `db:"name"`
	EntityTypeID int       `db:"entity_type_id"`
	CreatedAt    time.Time `db:"created_at"`
}

type EntityType struct {
	ID          int       `db:"id"`
	Name        string    `db:"name"`
	Description string    `db:"description"`
	CreatedAt   time.Time `db:"created_at"`
}

/*
	GENERIC MODELS
*/

// Entity represents a single entity
type Entity struct {
	Value      string `db:"value"`
	EntityType string `db:"entity_type"`
}

/*
	SOURCE TABLES
*/

// RawArticle represents raw table of news article in db
type RawArticle struct {
	AddedID      int            `db:"added_id"`
	SrcID        sql.NullString `db:"src_id"`
	ArticleType  sql.NullString `db:"article_type"`
	ImageURL     sql.NullString `db:"img_url"`
	Title        sql.NullString `db:"title"`
	PublishTime  sql.NullTime   `db:"publish_time"`
	PublishDate  sql.NullTime   `db:"publish_date"`
	Category     sql.NullString `db:"category"`
	Author       sql.NullString `db:"author"`
	ContentRaw   sql.NullString `db:"content_raw"`
	ContentText  sql.NullString `db:"content_text"`
	TagsRaw      sql.NullString `db:"tags_raw"`
	TagsText     sql.NullString `db:"tags_text"`
	Summary      sql.NullString `db:"summary"`
	LikeCount    sql.NullInt32  `db:"like_count"`
	DislikeCount sql.NullInt32  `db:"dislike_count"`
	RatingCount  sql.NullInt32  `db:"rating_count"`
	ViralCount   sql.NullInt32  `db:"viral_count"`
	CommentCount sql.NullInt32  `db:"comment_count"`
	TopicID      sql.NullInt32  `db:"topic_id"`
	PostedAt     time.Time      `db:"posted_at"`
	CreatedAt    time.Time      `db:"created_at"`
}
